#app engine MUST have the .yaml extension. Other cases either .yml or .yaml work

runtime: python39
entrypoint: gunicorn -b :$PORT --chdir app/ app.wsgi:application

handlers: ##<-- How to handle different URL requests
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto